### ISSUE TITLE
NullPointerException

### ISSUE THREAD

**Issue by 9autilus** [vcrawford/NetworkingProject#7]
```
[2017-04-08 20:36:42,868] [39m[DEBUG][0;39m [p.networking PeerProcess.java:115] peer starting (id = 1004)
[2017-04-08 20:36:42,868] [39m[DEBUG][0;39m [p.networking PeerProcess.java:233] reading common config
[2017-04-08 20:36:42,868] [39m[DEBUG][0;39m [p.networking PeerProcess.java:275] done reading common config
[2017-04-08 20:36:42,868] [39m[DEBUG][0;39m [p.networking PeerProcess.java:173] reading peer config
[2017-04-08 20:36:42,868] [39m[DEBUG][0;39m [p.networking PeerProcess.java:225] done reading peer config
[2017-04-08 20:36:42,883] [39m[DEBUG][0;39m [p.networking PeerProcess.java:317] Message handlers for peer 1004 have been registered.
[2017-04-08 20:36:42,883] [39m[DEBUG][0;39m [p.networking FileHandle.java:67] Peer 1004 has initiated a file handler with bitfield set to {}
[2017-04-08 20:36:42,883] [39m[DEBUG][0;39m [p.networking FileHandle.java:79] Peer 1001 bitfield initialized to {} (self=1004)
[2017-04-08 20:36:42,883] [39m[DEBUG][0;39m [p.networking FileHandle.java:79] Peer 1002 bitfield initialized to {} (self=1004)
[2017-04-08 20:36:42,883] [39m[DEBUG][0;39m [p.networking FileHandle.java:79] Peer 1003 bitfield initialized to {} (self=1004)
[2017-04-08 20:36:42,883] [39m[DEBUG][0;39m [p.networking FileHandle.java:79] Peer 1005 bitfield initialized to {} (self=1004)
[2017-04-08 20:36:42,883] [39m[DEBUG][0;39m [p.networking FileHandle.java:79] Peer 1006 bitfield initialized to {} (self=1004)
Exception in thread "AsynchronousSafe-1-dispatcher-1" [2017-04-08 20:36:42,883] [39m[DEBUG][0;39m [p.networking PeerProcess.java:694] Optimistic interval. Finding optimistic neighbor (self=1004)
com.mycila.event.SubscriberExecutionException[2017-04-08 20:36:42,883] [39m[DEBUG][0;39m [p.networking PeerProcess.java:735] No optimistic neighbor chosen (self=1004)

        at PeerProcess$UnchokeIntervalHandler.onEvent(PeerProcess.java:600)
        at com.mycila.event.internal.DefaultDispatcher$1$1.run(DefaultDispatcher.java:62)
        at com.mycila.event.Dispatchers$Executors$1.execute(Dispatchers.java:294)
        at com.mycila.event.internal.DefaultDispatcher$1.run(DefaultDispatcher.java:59)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at com.mycila.event.Dispatchers$DefaultThreadFactory$1.run(Dispatchers.java:362)
        at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.NullPointerException
        ... 8 more
[2017-04-08 20:36:42,899] [39m[DEBUG][0;39m [p.networking PeerProcess.java:286] Peer 1004 is beginning PeerListener
[2017-04-08 20:36:42,903] [39m[DEBUG][0;39m [p.networking PeerProcess.java:147] connecting to peers with lower ids
[2017-04-08 20:36:42,903] [39m[DEBUG][0;39m [p.networking PeerListener.java:46] Peer 1004 is waiting for 2 new peers to contact it
[2017-04-08 20:36:42,903] [39m[DEBUG][0;39m [p.networking PeerConnection.java:44] Initiating a peer connection with peer 1001 (self=1004)
[2017-04-08 20:36:42,903] [39m[DEBUG][0;39m [p.networking PeerConnection.java:44] Initiating a peer connection with peer 1002 (self=1004)
[2017-04-08 20:36:42,903] [39m[DEBUG][0;39m [p.networking PeerConnection.java:44] Initiating a peer connection with peer 1003 (self=1004)
[2017-04-08 20:36:42,907] [39m[DEBUG][0;39m [p.networking PeerProcess.java:165] 1004 is done initiating connections to peers with lower id
[2017-04-08 20:36:42,903] [34m[INFO][0;39m [p.networking PeerConnection.java:99] Peer 1004 makes a connection to Peer 1001
[2017-04-08 20:36:42,907] [34m[INFO][0;39m [p.networking PeerConnection.java:99] Peer 1004 makes a connection to Peer 1002
[2017-04-08 20:36:42,907] [34m[INFO][0;39m [p.networking PeerConnection.java:99] Peer 1004 makes a connection to Peer 1003
```
It doesn't affect the working, just the error message at the start of log. Not all peers give this error messaage.

**Comment by 9autilus** [comment]
Closing with `7be814c`
